"""
main.py
========

This module serves as the central orchestrator for the 'Autonomous Architect CLI' application.
It enables interaction with various LLM providers (e.g., Google Gemini, OpenAI) to execute user tasks,
manage conversational sessions, dynamically load and execute 'skills' (tools), and facilitate the
generation of new skill manifests. The application supports two primary modes: a command-line interface
(`run-task`, `generate-skill`) and an interactive chat loop for continuous interaction.

Key Responsibilities:
--------------------
- **Task Execution**: Drives the core conversational loop with the selected LLM for user task execution.
- **Skill Management**: Handles dynamic loading and integration of external tools/skills.
- **Session Management**: Maintains conversational context and state across interactions.
- **Error Handling & Logging**: Provides robust error handling and structured logging for operational stability.
- **Skill Generation**: Facilitates the creation of new skill manifests.
- **CLI Interface**: Exposes functionality via a command-line interface.

Components & Interactions:
--------------------------
- `ChesterRequest`/`ChesterResponse`: Data models for structured communication with the LLM.
- `Session`/`Model`: Manages session state and LLM model configuration.
- `architect`/`skill_creator` agents: Logic for generating system prompts and new skill manifests.
- `Skill`: Abstraction for managing and loading available tools.
- `argparse`: CLI parsing for `run-task` and `generate-skill` commands.
- `LLMClient` (new abstraction): Provides a uniform interface for different LLM providers.

"""
import logging
import os
import json
import sys
import argparse

# NOTE: `google.genai` is still imported because `genai.types.Part` is used by the request system.
# This will need further abstraction for full multi-provider tool support.
from google import genai

from core.request import ChesterRequest
from core.response import ChesterResponse, ChesterResponseException
from core.session import Model, Session
from .agents import architect, skill_creator
from .utils import write_skill_manifest
from .skill import Skill
from .clients import GeminiClient, LLMClient # Import the new LLM client abstraction

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# NOTE: The global 'client' and 'model' declarations have been removed.
# LLM client instances are now created and passed dynamically.

def get_client(provider: str, model: Model) -> LLMClient:
    """
    Dynamically selects and instantiates the appropriate LLM client.

    Args:
        provider (str): The name of the LLM provider (e.g., 'gemini', 'openai').
        model (Model): The specific model name to use (e.g., 'gemini-2.5-flash', 'gpt-4').

    Returns:
        LLMClient: An instance of the selected LLM client.

    Raises:
        ValueError: If an unsupported LLM provider is requested.
    """
    if provider.lower() == 'gemini':
        return GeminiClient(model = model)
    # TODO: Add more LLM providers here (e.g., elif provider.lower() == 'openai': return OpenAIClient(model_name=model))
    else:
        raise ValueError(f"Unsupported LLM provider: {provider}")

def run_gemini_task(session: Session, client: LLMClient, user_task: str) -> str:
    """
    Orchestrates the interaction with the LLM to execute a user task.

    This function manages the conversational turns, skill loading, command execution,
    and user interactions (information requests, command approvals) within a session.
    It iteratively sends requests to the LLM and processes its responses
    until the task is complete or an error occurs.

    Args:
        session (Session): The current conversational session object.
        client (LLMClient): The instantiated LLM client for communication with the model.
        user_task (str): The initial task provided by the user.

    Returns:
        str: The last message from the model, typically indicating task completion,
             a request for user input, or an error summary.
    """
    # Initialize a ChesterRequest with the system prompt generated by the architect agent.
    # The architect agent is responsible for understanding the user's task and available skills.
    # The client's model is passed to the architect to tailor the prompt if needed.
    request: ChesterRequest = ChesterRequest(
        system_prompt=architect(user_task=user_task, base_skills=Skill.all_headers(), absolute_path=os.getcwd()),
        skills={'unix-file-manipulation': Skill(name='unix-file-manipulation')},
        provider=client.model.value.split('-')[0], # Infer provider from model name for now
        model=client.model.value
    )
    logger.info(f"Using provider:{request.provider} | model: {request.model}")

    # Create a new chat session with the LLM client and system instructions.
    # The model name is retrieved from the client itself.
    session.set_client(client=client, system_instructions=request.system_prompt)

    # Update the session history with the initial user task.
    session.update_history(role='user', message=f'USER_TASK: {user_task}')

    max_turns = 30  # Maximum number of conversational turns to prevent infinite loops.
    turn = 0

    while True:
        turn += 1
        logger.info(f'--- TURN {turn} ---')
        if turn > max_turns:
            logger.warning('Exhausted session: Maximum turns reached without task completion.')
            break

        # Prepare skills to be loaded, converting their content to genai.types.Part objects.
        # This ensures the model is aware of available tools for its reasoning process.
        # TODO: Abstract genai.types.Part for full LLM provider agnosticism.
        skills_to_load = [genai.types.Part.from_text(text=v.content) for _, v in request.skills.items() if not v.loaded]
        #Add the skills to the last message in the conversation.
        session.append_message_to_last_user_interaction(skills_to_load)
        # Combine the last message from the session history with any skills to be loaded as parts for the LLM.
        request.parts = session.last_message_parts()
        
        try:

            # Parse the raw response text into a structured ChesterResponse object.
            response: ChesterResponse = client.send_message(messages=request.parts)
            
            # Update token usage tracking.
            session.token_tracker.update(response.usage_metadata)

            if response.is_complete:
                # If the model indicates the task is complete, update history and log success.
                session.update_history(role='model', message=response.response_to_user)
                logger.info('✅ Task Completed! The agent has finished the user task.')
                break
            else:
                # If the task is not complete, log the agent's thought process and update history.
                logger.info(f'Agent Thought: {response.thought}')
                session.update_history(role='model', message=response.thought)

            if response.needs_user_information:
                # If the agent needs user input, prompt the user and capture their response.
                response.user_response = input('Model requests you: ' + response.response_to_user +'\n. Your response:')

            if response.needs_approval:
                # If the agent requires approval for a command, log the command and prompt the user.
                logger.warning(f'Agent requires approval to proceed with the command: {response.command}')
                user_approval = input('Approve command? (yes/no): ')
                if user_approval.lower() != 'yes':
                    logger.warning('Command disapproved by user. Exiting task.')
                    session.update_history(role="user", message="Command disapproved by user")

            # Handle cases where no command is present and no user information is needed (potential JSON error from model).
            if not response.command and not response.needs_user_information:
                logger.warning('No command present in agent response, and no user information requested. Retrying with instruction.')
                session.update_history(role='user', message='Incorrect json. The command was not populated. Please provide a valid command or request user information.')
                continue

            if response.command:
                # If a command is present and approved, log it and execute it.
                logger.info(f'Executing command: {response.command}')
                response.command_result_output = response.command.execute()
                logger.debug(f'Command result output: {response.command_result_output}')

            if response.next_detected_skill_to_load and len(response.next_detected_skill_to_load) > 0:
                # If the agent requests loading new skills, add them to the request's skill set.
                for skill_name in response.next_detected_skill_to_load:
                    if skill_name not in request.skills.keys():
                        logger.info(f'Agent requests loading new skill: {skill_name}')
                        request.skills[skill_name] = Skill(name=skill_name)

            # Prepare the next input for the agent based on the command output or user response.
            next_agent_input_parts = [
                f'Continue with the task: {response.next_subtask}\n',
                f"OUTPUT:\t\n---\n\n{json.dumps({"user": response.user_response} if response.user_response else {"stdout":response.command_result_output.stdout, "stderr":response.command_result_output.stderr, "comment":response.command_result_output.is_safe }, indent=3)}\n\n---",
                f'LEARNINGS:{json.dumps(response.learnings)}'
            ]
            # Update the session history with the formatted input for the next turn.
            session.update_history(role='user', message='\n'.join(next_agent_input_parts))

        except ChesterResponseException:
            # Handle cases where the agent fails to provide valid JSON in its response.
            logger.error('Agent failed to provide valid JSON. Requesting retry...')
            session.update_history(
                role='user', message='Error: Your last response was not valid JSON. Please repeat using the strict JSON schema.')
            if turn >= max_turns:
                logger.error('Max turns reached due to persistent JSON errors. Exiting.')
                break
        except Exception as e:
            # Catch any other unexpected exceptions during the task execution.
            logger.exception('An unexpected error occurred during task execution:')
            session.update_history(role='user', message=f'Error: {str(e)}. Please try again or refine the task.')

    return session.last_assistant_message()


def generate_skill(client: LLMClient, skill_name: str, metadata: dict):
    """
    Generates a new skill manifest using the skill_creator agent.

    This function sends a request to the LLM, guided by the `skill_creator` agent,
    to produce a JSON-formatted skill manifest based on the provided skill name and metadata.
    The generated manifest is then written to the designated 'skills' directory.

    Args:
        client (LLMClient): The instantiated LLM client for communication with the model.
        skill_name (str): The name of the skill to generate.
        metadata (dict): A dictionary containing metadata for the skill, which will be
                         converted to a JSON string for the agent.
    """
    logger.info(f'Generating skill manifest for: {skill_name} with metadata: {metadata}')
    # Use the skill_creator agent to generate content for the new skill manifest.
    # The LLM's response will contain the JSON structure for the skill.
    response = client.generate_content(contents=skill_creator(skill=skill_name, metadata=metadata))
    # Write the generated content to a skill manifest file within the 'skills' directory.
    # The filename will be '{skill_name}.json'.
    write_skill_manifest(os.path.join(
        os.getcwd(), 'skills'), skill_name, response.text)
    logger.info(f'Skill manifest for {skill_name} created successfully.')


if __name__ == '__main__':
    # Ensure the script's directory is in the Python path for correct relative imports.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)

    # Set up argument parsing for command-line interface (CLI) commands.
    parser = argparse.ArgumentParser(description='Autonomous Architect CLI')
    subparsers = parser.add_subparsers(
        dest='command', help='Available commands')

    # --- Subparser for the 'run-task' command ---
    run_task_parser = subparsers.add_parser(
        'run-task', help='Run an LLM task with the agent')
    run_task_parser.add_argument(
        'user_task', type=str, help='The user task to execute')
    run_task_parser.add_argument('--session-file', type=str, default='session.txt',
                                 help='Path to the session file (default: session.txt)')
    # Allow specifying LLM provider and model, defaulting to Gemini
    run_task_parser.add_argument('--llm-provider', type=str, default='gemini',
                                 help='The LLM provider to use (e.g., "gemini", "openai"). Default: "gemini"')
    run_task_parser.add_argument('--llm-model', type=str, default='gemini-2.5-flash',
                                 help='The specific LLM model to use (e.g., "gemini-2.5-flash", "gpt-4"). Default: "gemini-2.5-flash"')

    # --- Subparser for the 'generate-skill' command ---
    generate_skill_parser = subparsers.add_parser(
        'generate-skill', help='Generate a new skill manifest')
    generate_skill_parser.add_argument(
        'skill_name', type=str, help='Name of the skill to generate')
    generate_skill_parser.add_argument(
        'metadata', type=str, help='Metadata for the skill as a JSON string')
    # Allow specifying LLM provider and model, defaulting to Gemini
    generate_skill_parser.add_argument('--llm-provider', type=str, default='gemini',
                                     help='The LLM provider to use (e.g., "gemini", "openai"). Default: "gemini"')
    generate_skill_parser.add_argument('--llm-model', type=str, default='gemini-2.5-flash',
                                     help='The specific LLM model to use (e.g., "gemini-2.5-flash", "gpt-4"). Default: "gemini-2.5-flash"')

    args = parser.parse_args()

    if args.command == 'run-task':
        # Handle the 'run-task' command: find or create a session and run the task.
        session = Session.find_or_create(is_new=True, session_id=None)
        logger.info(f'Starting run-task for user_task: {args.user_task} with provider: {args.llm_provider}, model: {args.llm_model}')
        # Dynamically instantiate the LLM client
        client = get_client(provider=args.llm_provider, model_name=args.llm_model)
        run_gemini_task(session=session, client=client, user_task=args.user_task)
        logger.info('Run-task completed.')
    elif args.command == 'generate-skill':
        # Handle the 'generate-skill' command: parse metadata and invoke skill generation.
        metadata_dict = json.loads(args.metadata)
        logger.info(f'Starting generate-skill for skill: {args.skill_name} with provider: {args.llm_provider}, model: {args.llm_model}')
        # Dynamically instantiate the LLM client
        client = get_client(provider=args.llm_provider, model= Model[args.llm_model])
        generate_skill(client=client, skill_name=args.skill_name, metadata=metadata_dict)
        logger.info(f'Generated skill {args.skill_name} successfully.')
    else:
        # Default interactive chat loop if no specific command is given.
        session: Session = Session.find_or_create(is_new=True, session_id=None)
        logger.info('Starting interactive chat loop.')
        while True:
            try:
                user_task = input('Architect> ')
                if user_task.lower() in ['exit', 'quit']:
                    logger.info('Exiting interactive chat.')
                    break
                # For the interactive loop, we can default to Gemini, or add input for provider/model
                # For now, default to Gemini
                client = get_client(provider='gemini', model=Model.gemini_2_5_flash) # Default LLM client for interactive mode.
                thought = run_gemini_task(session=session, client=client, user_task=user_task)
                logger.info(f'Model response: {thought}')
                session.token_tracker.report()
            except KeyboardInterrupt:
                logger.info('Interactive chat interrupted by user.')
                break
            except Exception as e:
                logger.exception('An error occurred in the interactive chat loop:')

